.TH FLUSH 8 
.ad
.fi
.SH NAME
flush
\-
Postfix fast flush cache manager
.SH SYNOPSIS
.na
.nf
\fBflush\fR [generic Postfix daemon options]
.SH DESCRIPTION
.ad
.fi
The flush server maintains a record of deferred mail by destination.
This information is used to improve the performance of the SMTP
\fBETRN\fR request, and of its command-line equivalent,
\fBsendmail -qR\fR.
This program expects to be run from the \fBmaster\fR(8) process
manager.

The record is implemented as per-destination logfiles with
as contents the queue IDs of deferred mail. The files are
append-only, and are truncated when delivery is requested
for a specific site.

Deferred mail by destination information is recorded only for
destinations that are eligible according to a configurable policy.
The policy is specified with the \fBfast_flush_cache_policy\fR
configuration parameter:
.IP \fBall\fR
Maintain per-destination deferred mail logfiles for all destinations.
.IP \fBrelay\fR
Maintain per-destination deferred mail logfiles only for destinations
that this system is willing to relay mail to ($\fBrelay_domains\fR).
.IP \fBnone\fR
Do not maintain per-destination deferred mail logfiles.
.PP
This server implements the following requests:
.IP "\fBFLUSH_REQ_ADD\fI sitename queue_id\fR"
Inform the cache manager that the specified message is queued for
the specified site. Depending on caching policy, the cache manager
stores or ignores the information.
.IP "\fBFLUSH_REQ_SEND\fI sitename\fR"
Request delivery of all messages that are queued for the specified
site. Depending on cache policy, this triggers delivery of specific
messages or of all queued mail. The per-destination logfile is
discarded.
.IP "\fBTRIGGER_REQ_WAKEUP\fR (wakeup signal from master)"
.IP "\fBFLUSH_REQ_PURGE\fR"
Delete empty per-destination logfiles that haven't been updated in
$\fBfast_flush_purge_delay\fR seconds.
.sp
Refresh non-empty per-destination logfiles that were not read in
$\fBfast_flush_refresh_delay\fR seconds. This is done by pretending
that send requests were received for the corresponding sites.
.sp
Fast flush logfiles are truncated only after a \fBFLUSH_REQ_SEND\fR
request, not when mail is actually delivered, and therefore can
accumulate outdated or redundant data. In order to maintain sanity,
\fBFLUSH_REQ_PURGE\fR should be requested at regular imtervals.
.sp
After an initial sanity check of request parameters, this request
proceeds in the background.
.PP
The response to the client is one of:
.IP \fBFLUSH_STAT_OK\fR
The request completed normally.
.IP \fBFLUSH_STAT_BAD\fR
The flush server rejected the request (bad request name, bad
request parameter value).
.IP \fBFLUSH_STAT_FAIL\fR
The request failed.
.SH SECURITY
.na
.nf
.ad
.fi
The fast flush server is not security-sensitive. It does not
talk to the network, and it does not talk to local users.
The fast flush server can run chrooted at fixed low privilege.
.SH DIAGNOSTICS
.ad
.fi
Problems and transactions are logged to \fBsyslogd\fR(8).
.SH BUGS
.ad
.fi
In reality, this server schedules delivery of all recipients
of deferred messages.  This limitation is due to the fact that
one queue runner has to handle mail for multiple destinations.
.SH FILES
.na
.nf
/var/spool/postfix/flush, location of "fast flush" logfiles.
.SH CONFIGURATION PARAMETERS
.na
.nf
.ad
.fi
See the Postfix \fBmain.cf\fR file for syntax details and for
default values. Use the \fBpostfix reload\fR command after a
configuration change.
.IP \fBfast_flush_cache_policy\fR
What destinations can have a "fast flush" logfile: \fBall\fR,
\fBrelay\fR (relay destinations) or \fBnone\fR.
.IP \fBfast_flush_refresh_delay\fR
Refresh a non-empty "fast flush" logfile that was not read in
this amount of time, by simulating a send request for the
corresponding destination.
.IP \fBfast_flush_purge_delay\fR
Remove an empty "fast flush" logfile that was not updated in
this amount of time.
.SH SEE ALSO
.na
.nf
smtpd(8) Postfix SMTP server
qmgr(8) Postfix queue manager
syslogd(8) system logging
.SH LICENSE
.na
.nf
.ad
.fi
The Secure Mailer license must be distributed with this software.
.SH AUTHOR(S)
.na
.nf
Wietse Venema
IBM T.J. Watson Research
P.O. Box 704
Yorktown Heights, NY 10598, USA
