.TH FLUSH 8 
.ad
.fi
.SH NAME
flush
\-
Postfix fast flush daemon
.SH SYNOPSIS
.na
.nf
\fBflush\fR [generic Postfix daemon options]
.SH DESCRIPTION
.ad
.fi
The flush server maintains so-called "fast flush" logfiles with
information about what messages are queued for a specific site.
This program expects to be run from the \fBmaster\fR(8) process
manager.

This server implements the following requests:
.IP "\fBFLUSH_REQ_ENABLE\fI sitename\fR"
Enable fast flush logging for the specified site.
.IP "\fBFLUSH_REQ_APPEND\fI sitename queue_id\fR"
Append \fIqueue_id\fR to the fast flush log for the
specified site.
.IP "\fBFLUSH_REQ_SEND\fI sitename\fR"
Arrange for the delivery of all messages that are listed in the fast
flush logfile for the specified site.  After the logfile is processed,
the file is truncated to length zero.
.PP
The response to the client is one of:
.IP \fBFLUSH_STAT_OK\fR
The request completed normally.
.IP \fBFLUSH_STAT_BAD\fR
The flush server rejected the request (bad request name, bad
request parameter value).
.IP \fBFLUSH_STAT_UNKNOWN\fR
The specified site has no fast flush log.
.PP
Fast flush logfiles are truncated only after a flush request. In
order to prevent fast flush logs from growing too large, and to
prevent them from accumulating too much outdated information, the
flush service generates a pro-active flush request once every
every 1000 append requests. This should not impact operation.
.SH SECURITY
.na
.nf
.ad
.fi
The fast flush server is not security-sensitive. It does not
talk to the network, and it does not talk to local users.
The fast flush server can run chrooted at fixed low privilege.
.SH DIAGNOSTICS
.ad
.fi
Problems and transactions are logged to \fBsyslogd\fR(8).
.SH BUGS
.ad
.fi
In reality, this server schedules delivery of messages, regardless
of their destination. This limitation is due to the fact that
one queue runner has to handle mail for multiple destinations.
.SH CONFIGURATION PARAMETERS
.na
.nf
.ad
.fi
The following \fBmain.cf\fR parameters are especially relevant to
this program. See the Postfix \fBmain.cf\fR file for syntax details
and for default values. Use the \fBpostfix reload\fR command after
a configuration change.
.IP \fBline_length_limit\fR
Maximal length of strings in a fast flush client request.
.SH SEE ALSO
.na
.nf
smtpd(8) Postfix SMTP server
qmgr(8) Postfix queue manager
syslogd(8) system logging
.SH LICENSE
.na
.nf
.ad
.fi
The Secure Mailer license must be distributed with this software.
.SH AUTHOR(S)
.na
.nf
Wietse Venema
IBM T.J. Watson Research
P.O. Box 704
Yorktown Heights, NY 10598, USA
