.TH POSTSCREEN 8 
.ad
.fi
.SH NAME
postscreen
\-
Postfix SMTP triage server
.SH "SYNOPSIS"
.na
.nf
\fBpostscreen\fR [generic Postfix daemon options]
.SH DESCRIPTION
.ad
.fi
The Postfix \fBpostscreen\fR(8) server performs triage on
multiple inbound SMTP connections in parallel. While a
single \fBpostscreen\fR(8) process keeps spambots away from
Postfix SMTP server processes, more Postfix SMTP server
processes remain available for legitimate clients.

\fBpostscreen\fR(8) maintains a temporary whitelist for
clients that have passed a number of tests.  When an SMTP
client IP address is whitelisted, \fBpostscreen\fR(8) hands
off the connection immediately to a Postfix SMTP server
process. This minimizes the overhead for legitimate mail.

By default, \fBpostscreen\fR(8) logs statistics and hands
off every connection to a Postfix SMTP server process, while
excluding clients in mynetworks from all tests (primarily,
to avoid problems with non-standard SMTP implementations
in network appliances).  This mode is useful for non-destructive
testing.

In a typical production setting, \fBpostscreen\fR(8) is
configured to reject mail from clients that fail one or
more tests. \fBpostscreen\fR(8) logs rejected mail with the
client address, helo, sender and recipient information.

\fBpostscreen\fR(8) is not an SMTP proxy; this is intentional.
The purpose is to keep spambots away from Postfix SMTP
server processes, while minimizing overhead for legitimate
traffic.
.SH "SECURITY"
.na
.nf
.ad
.fi
The \fBpostscreen\fR(8) server is moderately security-sensitive.
It talks to untrusted clients on the network. The process
can be run chrooted at fixed low privilege.
.SH "STANDARDS"
.na
.nf
RFC 5321 (SMTP, including multi-line 220 greetings)
RFC 2920 (SMTP Pipelining)
.SH DIAGNOSTICS
.ad
.fi
Problems and transactions are logged to \fBsyslogd\fR(8).
.SH BUGS
.ad
.fi
Some of the non-default protocol tests involve
\fBpostscreen\fR(8)'s built-in SMTP protocol engine. When
these tests succeed, \fBpostscreen\fR(8) adds the client
to the temporary whitelist but it cannot not hand off the
"live" connection to a Postfix SMTP server process in the
middle of a session.  Instead, \fBpostscreen\fR(8) defers
attempts to deliver mail with a 4XX status, and waits for
the client to disconnect.  The next time a good client
connects, it will be allowed to talk to a Postfix SMTP
server process to deliver mail. \fBpostscreen\fR(8) mitigates
the impact of this limitation by giving such tests a long
expiration time.

The \fBpostscreen\fR(8) built-in SMTP protocol engine does
not announce support for STARTTLS, AUTH, XCLIENT or XFORWARD
(support for STARTTLS and AUTH may be added in the future).
End-user clients should connect directly to the submission
service; other systems that require the above features
should directly connect to a Postfix SMTP server, or they
should be placed on the \fBpostscreen\fR(8) whitelist.
.SH "CONFIGURATION PARAMETERS"
.na
.nf
.ad
.fi
Changes to main.cf are not picked up automatically, as
\fBpostscreen\fR(8) processes may run for several hours.
Use the command "postfix reload" after a configuration
change.

The text below provides only a parameter summary. See
\fBpostconf\fR(5) for more details including examples.

NOTE: Some \fBpostscreen\fR(8)  parameters implement
stress-dependent behavior.  This is supported only when the
default value is stress-dependent (that is, it looks like
${stress?X}${stress:Y}).  Other parameters always evaluate
as if the stress value is the empty string.
.SH "TRIAGE PARAMETERS"
.na
.nf
.ad
.fi
.IP "\fBpostscreen_bare_newline_action (ignore)\fR"
The action that \fBpostscreen\fR(8) takes when an SMTP client sends
a bare newline character, that is, a newline not preceded by carriage
return.
.IP "\fBpostscreen_bare_newline_enable (no)\fR"
Enable "bare newline" SMTP protocol tests in the \fBpostscreen\fR(8)
server.
.IP "\fBpostscreen_blacklist_action (ignore)\fR"
The action that \fBpostscreen\fR(8) takes when an SMTP client is
permanently blacklisted with the postscreen_blacklist_networks
parameter.
.IP "\fBpostscreen_blacklist_networks (empty)\fR"
Network addresses that are permanently blacklisted; see the
postscreen_blacklist_action parameter for possible actions.
.IP "\fBpostscreen_disable_vrfy_command ($disable_vrfy_command)\fR"
Disable the SMTP VRFY command in the \fBpostscreen\fR(8) daemon.
.IP "\fBpostscreen_dnsbl_action (ignore)\fR"
The action that \fBpostscreen\fR(8) takes when an SMTP client's combined
DNSBL score is equal to or greater than a threshold (as defined
with the postscreen_dnsbl_sites and postscreen_dnsbl_threshold
parameters).
.IP "\fBpostscreen_dnsbl_reply_map (empty)\fR"
A mapping from actual DNSBL domain name which includes a secret
password, to the DNSBL domain name that postscreen will reply with
when it rejects mail.
.IP "\fBpostscreen_dnsbl_sites (empty)\fR"
Optional list of DNS blocklist domains, filters and weight
factors.
.IP "\fBpostscreen_dnsbl_threshold (1)\fR"
The inclusive lower bound for blocking an SMTP client, based on
its combined DNSBL score as defined with the postscreen_dnsbl_sites
parameter.
.IP "\fBpostscreen_forbidden_commands ($smtpd_forbidden_commands)\fR"
List of commands that the \fBpostscreen\fR(8) server considers in
violation of the SMTP protocol.
.IP "\fBpostscreen_greet_action (ignore)\fR"
The action that \fBpostscreen\fR(8) takes when an SMTP client speaks
before its turn within the time specified with the postscreen_greet_wait
parameter.
.IP "\fBpostscreen_greet_banner ($smtpd_banner)\fR"
The \fItext\fR in the optional "220-\fItext\fR..." server
response that
\fBpostscreen\fR(8) sends ahead of the real Postfix SMTP server's "220
text..." response, in an attempt to confuse bad SMTP clients so
that they speak before their turn (pre-greet).
.IP "\fBpostscreen_greet_wait (${stress?2}${stress:6}s)\fR"
The amount of time that \fBpostscreen\fR(8) will wait for an SMTP
client to send a command before its turn, and for DNS blocklist
lookup results to arrive (default: up to 2 seconds under stress,
up to 6 seconds otherwise).
.IP "\fBpostscreen_helo_required ($smtpd_helo_required)\fR"
Require that a remote SMTP client sends HELO or EHLO before
commencing a MAIL transaction.
.IP "\fBpostscreen_non_smtp_command_action (drop)\fR"
The action that \fBpostscreen\fR(8) takes when an SMTP client sends
non-SMTP commands as specified with the postscreen_forbidden_commands
parameter.
.IP "\fBpostscreen_non_smtp_command_enable (no)\fR"
Enable "non-SMTP command" tests in the \fBpostscreen\fR(8) server.
.IP "\fBpostscreen_pipelining_action (enforce)\fR"
The action that \fBpostscreen\fR(8) takes when an SMTP client sends
multiple commands instead of sending one command and waiting for
the server to respond.
.IP "\fBpostscreen_pipelining_enable (no)\fR"
Enable "pipelining" SMTP protocol tests in the \fBpostscreen\fR(8)
server.
.IP "\fBpostscreen_whitelist_networks ($mynetworks)\fR"
Network addresses that are permanently whitelisted, and that
will not be subjected to \fBpostscreen\fR(8) checks.
.IP "\fBsmtpd_service_name (smtpd)\fR"
The internal service that \fBpostscreen\fR(8) forwards allowed
connections to.
.SH "CACHE CONTROLS"
.na
.nf
.ad
.fi
.IP "\fBpostscreen_cache_cleanup_interval (12h)\fR"
The amount of time between \fBpostscreen\fR(8) cache cleanup runs.
.IP "\fBpostscreen_cache_map (btree:$data_directory/ps_cache)\fR"
Persistent storage for the \fBpostscreen\fR(8) server decisions.
.IP "\fBpostscreen_cache_retention_time (7d)\fR"
The amount of time that \fBpostscreen\fR(8) will cache an expired
temporary whitelist entry before it is removed.
.IP "\fBpostscreen_bare_newline_ttl (30d)\fR"
The amount of time that \fBpostscreen\fR(8) will cache results from
a successful "bare newline" SMTP protocol test.
.IP "\fBpostscreen_dnsbl_ttl (1h)\fR"
The amount of time that \fBpostscreen\fR(8) will cache results from
a successful DNS blocklist test.
.IP "\fBpostscreen_greet_ttl (1d)\fR"
The amount of time that \fBpostscreen\fR(8) will cache results from
a successful PREGREET test.
.IP "\fBpostscreen_non_smtp_command_ttl (30d)\fR"
The amount of time that \fBpostscreen\fR(8) will cache results from
a successful "non_smtp_command" SMTP protocol test.
.IP "\fBpostscreen_pipelining_ttl (30d)\fR"
The amount of time that \fBpostscreen\fR(8) will cache results from
a successful "pipelining" SMTP protocol test.
.SH "RESOURCE CONTROLS"
.na
.nf
.ad
.fi
.IP "\fBline_length_limit (2048)\fR"
Upon input, long lines are chopped up into pieces of at most
this length; upon delivery, long lines are reconstructed.
.IP "\fBpostscreen_client_connection_count_limit ($smtpd_client_connection_count_limit)\fR"
How many simultaneous connections any client is allowed to have
with the \fBpostscreen\fR(8) daemon.
.IP "\fBpostscreen_command_count_limit (20)\fR"
The limit on the total number of commands per SMTP session for
\fBpostscreen\fR(8)'s built-in SMTP protocol engine.
.IP "\fBpostscreen_command_time_limit (${stress?10}${stress:300}s)\fR"
The command "read" time limit for \fBpostscreen\fR(8)'s built-in SMTP
protocol engine.
.IP "\fBpostscreen_post_queue_limit ($default_process_limit)\fR"
The number of clients that can be waiting for service from a
real SMTP server process.
.IP "\fBpostscreen_pre_queue_limit ($default_process_limit)\fR"
The number of non-whitelisted clients that can be waiting for
a decision whether they will receive service from a real SMTP server
process.
.IP "\fBpostscreen_watchdog_timeout (10s)\fR"
How much time a \fBpostscreen\fR(8) process may take to respond to
an SMTP client command or to perform a cache operation before it
is terminated by a built-in watchdog timer.
.SH "MISCELLANEOUS CONTROLS"
.na
.nf
.ad
.fi
.IP "\fBconfig_directory (see 'postconf -d' output)\fR"
The default location of the Postfix main.cf and master.cf
configuration files.
.IP "\fBdelay_logging_resolution_limit (2)\fR"
The maximal number of digits after the decimal point when logging
sub-second delay values.
.IP "\fBcommand_directory (see 'postconf -d' output)\fR"
The location of all postfix administrative commands.
.IP "\fBipc_timeout (3600s)\fR"
The time limit for sending or receiving information over an internal
communication channel.
.IP "\fBmax_idle (100s)\fR"
The maximum amount of time that an idle Postfix daemon process waits
for an incoming connection before terminating voluntarily.
.IP "\fBprocess_id (read-only)\fR"
The process ID of a Postfix command or daemon process.
.IP "\fBprocess_name (read-only)\fR"
The process name of a Postfix command or daemon process.
.IP "\fBsyslog_facility (mail)\fR"
The syslog facility of Postfix logging.
.IP "\fBsyslog_name (see 'postconf -d' output)\fR"
The mail system name that is prepended to the process name in syslog
records, so that "smtpd" becomes, for example, "postfix/smtpd".
.SH "SEE ALSO"
.na
.nf
smtpd(8), Postfix SMTP server
dnsblog(8), temporary DNS helper
syslogd(8), system logging
.SH "README FILES"
.na
.nf
.ad
.fi
Use "\fBpostconf readme_directory\fR" or "\fBpostconf
html_directory\fR" to locate this information.
.nf
.na
POSTSCREEN_README, Postfix Postscreen Howto
.SH "LICENSE"
.na
.nf
.ad
.fi
The Secure Mailer license must be distributed with this software.
.SH "HISTORY"
.na
.nf
.ad
.fi
Many ideas in \fBpostscreen\fR(8) were explored in earlier
work by Michael Tokarev, in OpenBSD spamd, and in MailChannels
Traffic Control.
.SH "AUTHOR(S)"
.na
.nf
Wietse Venema
IBM T.J. Watson Research
P.O. Box 704
Yorktown Heights, NY 10598, USA
