#!/bin/sh

# Finds double words in install and proto text files.

LANG=C; export LANG

ls *install* proto/* | egrep -v 'stop|Makefile|html|\.proto' | xargs mantools/deroff | mantools/find-double | fgrep -vxf proto/stop.double-install-proto-text
