#!/bin/sh

# Spellchecks text in the HISTORY file, starting with 2022.

LANG=C; export LANG

sed '1,/^2022/d' HISTORY | spell | fgrep -vxf proto/stop | \
	fgrep -vxf proto/stop.spell-cc | \
	fgrep -vxf proto/stop.spell-history
