#!/bin/sh

version=$(basename $(env - pwd)) || exit 1
case "$version" in
postfix-[0-9]*.[0-9]*.[0-9]*) 
    test -f conf/makedefs.out || {
	echo "Error: no conf/makedefs.out" 1>&2; exit 1; }
    grep 'CCARGS.*-DSNAPSHOT' conf/makedefs.out && {
	echo "Error: stable release builds with -DSNAPSHOT" 1>&2, exit 1; }
    grep 'CCARGS.*-DNONPROD' conf/makedefs.out && {
	echo "Error: stable release builds with -DNONPROD" 1>&2, exit 1; }
    ;;
esac
