#!/bin/sh

# Spellchecks the install scripts and proto non-html files.

LANG=C; export LANG

ls *install* proto/* | egrep -v 'stop|Makefile|html|\.proto' |  mantools/deroff | spell | fgrep -vxf proto/stop
