    VAR_SENDMAIL_PATH, DEF_SENDMAIL_PATH, &var_sendmail_path, 1, 0,
    VAR_MAILQ_PATH, DEF_MAILQ_PATH, &var_mailq_path, 1, 0,
    VAR_NEWALIAS_PATH, DEF_NEWALIAS_PATH, &var_newalias_path, 1, 0,
    VAR_CONFIG_DIR, DEF_CONFIG_DIR, &var_config_dir, 1, 0,
    VAR_MANPAGE_PATH, DEF_MANPAGE_PATH, &var_manpage_path, 1, 0,
