#!/bin/sh

# Sample Postfix installation script. Run this from the top-level
# Postfix source directory.

PATH=/bin:/usr/bin:/usr/sbin:/usr/etc:/sbin:/etc
umask 022

# Default settings, edit to taste or change interactively. Once this
# script has run it saves settings to $config_directory/install.cf.

config_directory=/etc/postfix
daemon_directory=/usr/libexec/postfix
command_directory=/usr/sbin
queue_directory=/var/spool/postfix
sendmail_path=/usr/sbin/sendmail
newaliases_path=/usr/bin/newaliases
mailq_path=/usr/bin/mailq
mail_owner=postfix
setgid=no
manpages=no

# Load defaults from existing installation.

test -f $config_directory/main.cf && {
    for name in daemon_directory command_directory queue_directory mail_owner 
    do
	eval "$name=\"\`bin/postconf -h $name || kill \$\$\`\""
    done
}

test -f $config_directory/install.cf && . $config_directory/install.cf

cat <<EOF

Warning: this script replaces existing sendmail or Postfix programs.
Make backups if you want to be able to recover.

In addition to doing a fresh install, this script can change an
existing installation from using a world-writable maildrop to a
group-writable one. It cannot be used to change Postfix queue
ownership.

Before installing files, this script prompts you for some definitions.
You can either edit this script ahead of time, or you can specify
your changes interactively.

    config_directory - directory with Postfix configuration files.
    daemon_directory - directory with Postfix daemon programs.
    command_directory - directory with Postfix administrative commands.
    queue_directory - directory with Postfix queues.

    sendmail_path - full pathname of the Postfix sendmail command.
    newaliases_path - full pathname of the Postfix newaliases command.
    mailq_path - full pathname of the Postfix mailq command.

    mail_owner - owner of Postfix queue files.

    setgid - groupname, e.g., postdrop (default: no). See INSTALL section 12.
    manpages - path to man tree (default: no). Example: /usr/local/man.

EOF

# By now, shells must have functions. Ultrix users must use sh5 or lose.

compare_or_replace() {
    cmp $2 $3 >/dev/null 2>&1 || {
	cp $2 junk || exit 1
	mv -f junk $3 || exit 1
	chmod $1 $3 || exit 1
    }
}

compare_or_symlink() {
    cmp $1 $2 >/dev/null 2>&1 || {
	ln -s $1 junk || exit 1
	mv -f junk $2 || exit 1
    }
}

compare_or_move() {
    cmp $2 $3 >/dev/null 2>&1 || {
	mv -f $2 $3 || exit 1
	chmod $1 $3 || exit 1
    }
}

# How to supress newlines in echo

case `echo -n` in
"") n=-n; c=;;
 *) n=; c='\c';;
esac

for name in config_directory daemon_directory command_directory \
    queue_directory sendmail_path newaliases_path mailq_path mail_owner \
    setgid manpages
do
    while :
    do
	eval echo \$n "$name: [\$$name]\  \$c"
	read ans
	case $ans in
	"") break;;
	 *) eval $name=\$ans; break;;
	esac
    done
done

# Sanity checks

for path in $config_directory $daemon_directory $command_directory \
    $queue_directory $sendmail_path $newaliases_path $mailq_path $manpages
do
   case $path in
   /*) ;;
   no) ;;
    *) echo "$path should be an absolute path name" 1>&2; exit 1;;
   esac
done

# Create any missing directories.

test -d $config_directory || mkdir -p $config_directory || exit 1
test -d $daemon_directory || mkdir -p $daemon_directory || exit 1
test -d $command_directory || mkdir -p $command_directory || exit 1
test -d $queue_directory || mkdir -p $queue_directory || exit 1

# Install files. Be careful to not copy over running programs.

for file in `ls libexec`
do
    compare_or_replace a+x,go-w libexec/$file $daemon_directory/$file || exit 1
done

for file in `ls bin | grep '^post'`
do
    compare_or_replace a+x,go-w bin/$file $command_directory/$file || exit 1
done

test -f bin/sendmail && {
    compare_or_replace a+x,go-w bin/sendmail $sendmail_path || exit 1
    compare_or_symlink $sendmail_path $newaliases_path
    compare_or_symlink $sendmail_path $mailq_path
}

compare_or_replace a+r,go-w conf/LICENSE $config_directory/LICENSE || exit 1

test -f $config_directory/main.cf || {
    cp conf/* $config_directory || exit 1
    chmod a+r,go-w $config_directory/* || exit 1

    echo "Warning: you still need to edit myorigin/mydestination in" 1>&2
    echo "$config_directory/main.cf. See also html/faq.html for dialup" 1>&2
    echo "sites or for sites inside a firewalled network." 1>&2
    echo "" 1>&2
    echo "BTW, Edit your alias database and be sure to set up aliases" 1>&2
    echo "for root and postmaster, then run the newaliases command." 1>&2
}

# Save settings.

postconf -e \
    "daemon_directory = $daemon_directory" \
    "command_directory = $command_directory" \
    "queue_directory = $queue_directory" \
    "mail_owner = $mail_owner" \
|| exit 1

(echo "# This file was generated by $0"
for name in config_directory sendmail_path newaliases_path mailq_path \
    setgid manpages
do
    eval echo $name=\$$name
done) >junk || exit 1
compare_or_move a+x,go-w junk $config_directory/install.cf || exit 1
rm -f junk

# Use set-gid privileges instead of writable maildrop (optional).

test -d $queue_directory/maildrop || {
    mkdir -p $queue_directory/maildrop || exit 1
    chown $owner $queue_directory/maildrop || exit 1
}

case $setgid in
no)
    chmod 1733 $queue_directory/maildrop || exit 1
    chmod g-s $command_directory/postdrop || exit 1
    postfix_script=conf/postfix-script-nosgid
    ;;
 *) 
    chgrp $setgid $command_directory/postdrop || exit 1
    chmod g+s $command_directory/postdrop || exit 1
    chgrp $setgid $queue_directory/maildrop || exit 1
    chmod 1730 $queue_directory/maildrop || exit 1
    postfix_script=conf/postfix-script-sgid
    ;;
esac

compare_or_replace a+x,go-w $postfix_script $config_directory/postfix-script ||
    exit 1

# Install manual pages (optional). We just clobber whatever is there.

case $manpages in
no) ;;
 *) (
     cd man || exit 1
     for dir in man?
	 do mkdir -p $manpages/$dir || exit 1
     done
     for file in man?/*
     do
	 rm -f $manpages/$file
	 cp $file $manpages/$file || exit 1
	 chmod 644 $manpages/$file || exit 1
     done
    )
esac
